service: website-jakoberpf
# app and org for use with dashboard.serverless.com
#app: jakoberpf
#org: jakoberpf

useDotenv: true

frameworkVersion: '2'

plugins:
  - serverless-s3-sync
  - serverless-export-env
  - serverless-cloudflare-dns

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  stage: ${opt:stage}
  lambdaHashingVersion: 20201221

  environment:
    CLOUDFRONT_ID: !Ref WebsiteDistribution

custom: 

  bucketName: ${self:service}-${self:provider.region}-${self:provider.stage}
  domainName: ${env:SLS_DOMAIN_NAME}
  certificateArn: ${env:SLS_CERT_ARN}

  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: out/


resources:
  - ${file(resources/s3-bucket.yml)}
  - ${file(resources/cdn-distribution.yml)}

