name: Deploy on Live
on:
  push:
    branches:
      - main
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Create env file
      run: |
        cat > .env << EOF
        AWS_ACCESS_KEY_ID=${{ secrets.LIVE_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY=${{ secrets.LIVE_AWS_SECRET_ACCESS_KEY }}
        SLS_DOMAIN_NAME=${{ secrets.LIVE_SLS_DOMAIN_NAME }}
        SLS_CERT_ARN=${{ secrets.LIVE_SLS_CERT_ARN }}
        CLF_TOKEN=${{ secrets.$LIVE_CLF_TOKEN }}
        EOF
    - name: Install Yarn Package Manager
      run: npm install -g yarn
    - name: Install Serverless Framework
      run: npm install -g serverless@2
    - name: Install NPM dependencies
      run: yarn install
    - name: Build assets
      run: yarn build
    - name: Deploy
      run: sls deploy --stage live
    # - name: Invalidate Cloudfront
    #   run: sls export-env & aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"